### ISSUE TITLE
exec function PHP error

### ISSUE THREAD

**Issue by ghost** [mrimann/CoMo#26]
metadataextractor:processrepositories function sends 'Only variables can be passed by reference' in MetaDataExtractorCommandController.php at line 183
"exec ('git pull', NULL, $pullResult);"

**Comment by mrimann** [comment]
What PHP version are you running CoMo on?
Any special PHP configuration?

Is the monitored repo public so I could give it a try to reproduce your issue?

**Comment by ghost** [comment]
1. PHP version is 5.5.10.
2. No special php configuration.
3. Sorry but the repo is private, however it happened with all the repositories that i tried.
   Simply replacing NULL with an empty unused variable seems to work though.

**Comment by mrimann** [comment]
Ok, I'll give it a try when I find a moment of time. Thanks for reporting the issue!

**Comment by mrimann** [comment]
Fixed in v1.1.1 and will be in v1.2.0 too.
